server:
  port:8080
spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto:create
      globally_quoted_identifiers:'true'
  datasource:
#        username: postgres
#        url: jdbc:postgresql://localhost:5432/localhost
#        password: Dnamodel10@
    username: tiger
    url: jdbc:postgresql://nafa.cp4e12t7aiyi.us-east-2.rds.amazonaws.com/registration
    password: nafatiger
#  mail:
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: 'true'
#          auth: 'true'
#    host: smtp.gmail.com
#    username: thapakhaji5@gmail.com
#    password: eeeysijpgnftcgmb
#    port: '587'
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: 
      secret-key: 

jwt:
  auth:
    secret_key: testkey#secret@12334
    expires_in: '3600'
    app: Spring-Security-App


