server:
   port:8082
spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: 'true'
    hibernate:
      ddl-auto:create
      globally_quoted_identifiers:'true'
  datasource:
    username: tiger
    url: jdbc:postgresql://nafa.cd88dvneqxaz.us-east-1.rds.amazonaws.com/registration
    password: 9Billions$
jwt:
  auth:
    secret_key: testkey#secret@12334
    expires_in: '3600'
    app: Spring-Security-App
  